backend:
  name: git-gateway
  branch: main # Cambia a "master" si tu rama principal se llama master

media_folder: "images" # Donde se guardar치n las im치genes
public_folder: "/images" # Ruta p칰blica de las im치genes

collections:
  # Colecci칩n para rese침as de Apps
  - name: "apps"
    label: "游님 Apps Recomendadas"
    folder: "_posts/apps"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "T칤tulo", name: "title", widget: "string"}
      - {label: "Fecha de Publicaci칩n", name: "date", widget: "datetime"}
      - {label: "Imagen Principal", name: "featured_image", widget: "image"}
      - {label: "Categor칤a", name: "category", widget: "select", options: ["ADHD", "Autismo", "Organizaci칩n", "Productividad", "Bienestar"]}
      - {label: "Puntuaci칩n (1-5)", name: "rating", widget: "number", min: 1, max: 5}
      - {label: "Precio", name: "price", widget: "string"}
      - {label: "Link de Afiliado", name: "affiliate_link", widget: "string"}
      - {label: "Pros", name: "pros", widget: "list"}
      - {label: "Contras", name: "cons", widget: "list"}
      - {label: "Descripci칩n Corta", name: "excerpt", widget: "text"}
      - {label: "Rese침a Completa", name: "body", widget: "markdown"}

  # Colecci칩n para Libros
  - name: "libros"
    label: "游닄 Libros Recomendados"
    folder: "_posts/libros"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "T칤tulo del Libro", name: "title", widget: "string"}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Fecha de Publicaci칩n", name: "date", widget: "datetime"}
      - {label: "Portada del Libro", name: "featured_image", widget: "image"}
      - {label: "G칠nero", name: "genre", widget: "select", options: ["Neurociencia", "Parentalidad", "Autoayuda", "Biograf칤a", "Educaci칩n"]}
      - {label: "Puntuaci칩n (1-5)", name: "rating", widget: "number", min: 1, max: 5}
      - {label: "Link de Compra (Afiliado)", name: "buy_link", widget: "string"}
      - {label: "ISBN", name: "isbn", widget: "string", required: false}
      - {label: "Resumen", name: "excerpt", widget: "text"}
      - {label: "Rese침a Completa", name: "body", widget: "markdown"}

  # Colecci칩n para Tips
  - name: "tips"
    label: "游눠 Tips y Consejos"
    folder: "_posts/tips"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "T칤tulo del Tip", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Imagen", name: "featured_image", widget: "image", required: false}
      - {label: "Categor칤a", name: "category", widget: "select", options: ["Organizaci칩n", "Rutinas", "Productividad", "Autocuidado", "Tecnolog칤a"]}
      - {label: "Tiempo de Lectura (min)", name: "read_time", widget: "number"}
      - {label: "Resumen", name: "excerpt", widget: "text"}
      - {label: "Contenido", name: "body", widget: "markdown"}

  # Colecci칩n para Gadgets
  - name: "gadgets"
    label: "游댢 Gadgets y Herramientas"
    folder: "_posts/gadgets"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Nombre del Producto", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Imagen Principal", name: "featured_image", widget: "image"}
      - {label: "Marca", name: "brand", widget: "string"}
      - {label: "Precio Aproximado", name: "price", widget: "string"}
      - {label: "Link de Compra (Afiliado)", name: "affiliate_link", widget: "string"}
      - {label: "Categor칤a", name: "category", widget: "select", options: ["Organizaci칩n", "Tecnolog칤a", "Hogar", "Oficina", "Bienestar"]}
      - {label: "Puntuaci칩n (1-5)", name: "rating", widget: "number", min: 1, max: 5}
      - {label: "Descripci칩n", name: "excerpt", widget: "text"}
      - {label: "Rese침a Detallada", name: "body", widget: "markdown"}
